### ISSUE TITLE
using home?

### ISSUE THREAD

**Issue by watkinsr** [bobvanderlinden/nixos-config#1]
Hi, sorry to bother you bob.

Just curious as to how I might use the home config you have? I guess you've deprecated the general configuration.nix in favor of it? Or do you use them in tandem?

**Comment by bobvanderlinden** [comment]
Hi, sorry for the late reply :sweat_smile: I've added a readme now: https://github.com/bobvanderlinden/nixos-config Does that include the information you're after?
